name: gabithume
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12958
title: gabithume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fae4b2'
    - '#2a3748'
    - '#dca05a'
    - '#6f7d63'
    - '#e33f57'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
