typography_spectrum: 0.6611
color:
  brandColors:
    - '#fae4b2'
    - '#2a3748'
    - '#dca05a'
    - '#6f7d63'
    - '#e33f57'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: ''
  email: gabithume@gmail.com
  name: Gabriela Thumé
name: gabithume
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
favicon: null
title: gabithume
purpose: []
