name: gabithume
favicon: null
layout_spectrum: 0.81579
typography_spectrum: 0.60526
title: gabithume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d5e5b'
    - '#bebcbc'
    - '#212020'
    - '#9a8c89'
    - '#463c3b'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
