name: gabithume
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: gabithume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#f71835"
    - "#ffa042"
    - "#b1e8a5"
    - "#3a2a2d"
    - "#658659"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
